---
image: alpine/edge
secrets:
  - 5077f4a0-6a32-46e8-aa7c-5be8778d0524
sources:
  - git@git.sr.ht/~a14m/ansible-rc-playbooks
environment:
  GIT_SSH_COMMAND: ssh -o StrictHostKeyChecking=no
tasks:
  - setup: |
      # This is for not having to cd into your <repo> for each task
      echo 'cd ansible-rc-playbooks' >> ~/.buildenv
  - check: |
      if [ "$(git rev-parse origin/main)" != "$(git rev-parse HEAD)" ]; then \
        complete-build; \
      fi
  - mirror: |
      git push --force --mirror git@github.com:a14m/ansible-rc-playbooks.git
