---
- name: "Setting user_groups"
  ansible.builtin.set_fact:
    sudo_group: "sudo"
  tags: [required_for_boot]

- name: "Configure permissions for {{ sudo_group }}"
  become: true
  community.general.sudoers:
    name: "enable-sudo-group"
    group: "{{ sudo_group }}"
    commands: "ALL"
    nopassword: false
    sudoers_path: "/etc/sudoers.d"
    state: present
  tags: [required_for_boot]

- name: "Ensure user_groups are created"
  become: true
  ansible.builtin.group:
    name: "{{ item }}"
    state: "present"
  with_items:
    - "{{ username }}"
    - "{{ sudo_group }}"
  tags: [required_for_boot]

- name: "Create user {{ username }}"
  become: true
  ansible.builtin.user:
    name: "{{ username }}"
    append: false
    create_home: true
    generate_ssh_key: false
    groups: "{{ [username, sudo_group] }}"
    password: "{{ user_password }}"
    state: "present"
    update_password: "on_create"
  register: user
  notify: "Require password change"
  tags: [required_for_boot]

- name: "Create user ssh directory"
  ansible.builtin.file:
    path: "/home/{{ username }}/.ssh/"
    mode: "0700"
    owner: "{{ username }}"
    state: "directory"
  tags: [required_for_boot]

- name: "Add user ssh authorized_keys"
  ansible.builtin.copy:
    dest: "/home/{{ username }}/.ssh/authorized_keys"
    mode: "0600"
    owner: "{{ username }}"
    content: |
      {{ user_public_keys | join('\n') }}
  tags: [required_for_boot]
