---
- name: "Install OS-specific packages"
  ansible.builtin.include_tasks: "install-{{ ansible_os_family | lower }}.yml"
  tags: [required_for_boot]

- name: "Configure user"
  ansible.builtin.include_tasks: "configure.yml"
  tags: [required_for_boot]
