---
role_name_check: 1
dependency:
  name: galaxy
  options:
    ignore-errors: true
driver:
  name: docker
platforms:
  - name: instance
    image: ${MOLECULE_DISTRO:-archlinux}
    dockerfile: Dockerfile.${MOLECULE_DISTRO:-archlinux}.j2
    pre_build_image: false
    privileged: true
    command: ${MOLECULE_COMMAND:-""}
    tmpfs:
      - "/tmp"
      - "/run"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
      - "/srv:/srv:rw"
      - "/dev:/dev:rw"
    cgroupns_mode: host
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "../../roles"
  config_options:
    defaults:
      fact_caching: jsonfile
      fact_caching_connection: /tmp/facts_cache
      fact_caching_timeout: 120
  playbooks:
    converge: converge.yml
verifier:
  name: ansible
