---
- name: Prepare
  hosts: localhost
  gather_facts: true
  tasks:
    - name: "Create virtual disk image"
      become: true
      community.general.filesize:
        path: "/opt/vdd.img"
        size: 8G
        mode: "0755"
        force: true

    - name: "Create test_device (loop block device)"
      become: true
      ansible.builtin.command:
        cmd: "losetup --show -Pf /opt/vdd.img"
      register: loop_device
      changed_when: true

    - name: "Set test_device"
      ansible.builtin.set_fact:
        test_device: "{{ loop_device.stdout }}"
        cacheable: true

    - name: "Show test_device"
      ansible.builtin.debug:
        msg: "{{ test_device }}"

    - name: "Prepare distro-configure.yml"
      ansible.builtin.copy:
        src: "../../distro-configure.yml.example"
        dest: "../../distro-configure.yml"
        remote_src: false
        force: false
        mode: "0644"
