---
live_environments:
  vars:
    ansible_user: root
    ansible_connection: ssh
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
  hosts:
    archlinuxiso.local:
    ubuntuiso.local:

vlan:
  vars:
    ansible_connection: ssh
  hosts:
    archlinux.local:
    ubuntu.local:
