---
argument_specs:
  main:
    options:
      hostname:
        type: "str"
        default: "{{ inventory_hostname }}"
        description: "The distro linux hostname to be configured"
      group_roles:
        type: "list"
        description: "The list of roles to configure for all hosts in a group"
        elements: "str"
        default: []
      host_roles:
        type: "list"
        description: "The list of roles to configure specific host in a group"
        elements: "str"
        default: []
