---
dependencies: []
galaxy_info:
  role_name: partition
  author: a14m
  description: "Create and manage device partitions"
  company: "kartoffeln.work GmbH."
  license: "license MIT"
  min_ansible_version: "2.18"
  platforms:
    - name: ArchLinux
      versions:
        - all
