---
- name: "Ensure sshd installed"
  community.general.pacman:
    name: "{{ ssh_package_name }}"
    state: present

- name: "Ensure sshd is enabled"
  ansible.builtin.service:
    name: "{{ ssh_service_name }}"
    state: "started"
    enabled: true
  when: not ansible_is_chroot

- name: "(chroot): Ensure ssh_service enabled"
  # noqa: command-instead-of-module intentional isnide chroot
  ansible.builtin.command:
    cmd: "systemctl enable {{ ssh_service_name }}"
  when: ansible_is_chroot
  changed_when: true

- name: "Generate /etc/ssh/ RSA host key"
  ansible.builtin.command:
    cmd: "ssh-keygen -q -t rsa -b 4096 -f /etc/ssh/ssh_host_rsa_key -C '' -N ''"
    creates: "/etc/ssh/ssh_host_rsa_key"

- name: "Generate /etc/ssh/ ECDSA host key"
  ansible.builtin.command:
    cmd: "ssh-keygen -q -t ecdsa -b 521 -f /etc/ssh/ssh_host_ecdsa_key -C '' -N ''"
    creates: "/etc/ssh/ssh_host_ecdsa_key"

- name: "Generate /etc/ssh/ Ed25519 host key"
  ansible.builtin.command:
    cmd: "ssh-keygen -q -t ed25519 -f /etc/ssh/ssh_host_ed25519_key -C '' -N ''"
    creates: "/etc/ssh/ssh_host_ed25519_key"

- name: "Configure ssh defaults"
  ansible.builtin.copy:
    dest: "/etc/ssh/sshd_config.d/99-archlinux.conf"
    mode: "0640"
    content: |
      # sshd_config defaults on Arch Linux
      KbdInteractiveAuthentication no
      UsePAM no         # default is yes
      PrintMotd yes     # default is no
      # Host key configurations
      HostKey /etc/ssh/ssh_host_rsa_key
      HostKey /etc/ssh/ssh_host_ecdsa_key
      HostKey /etc/ssh/ssh_host_ed25519_key

- name: "Configure authentication policy"
  ansible.builtin.copy:
    dest: "/etc/ssh/sshd_config.d/99-auth-policy.conf"
    mode: "0640"
    validate: "sshd -T -f %s"
    content: |
      Port {{ ssh_port }}
      PasswordAuthentication no
      AuthenticationMethods publickey
      PermitRootLogin no
      PermitEmptyPasswords no
      ChallengeResponseAuthentication no
      GSSAPIAuthentication no
      X11Forwarding no
  notify:
    - "Reload systemd"
    - "Restart ssh"

- name: "Add arg.username to allowed users"
  ansible.builtin.copy:
    dest: "/etc/ssh/sshd_config.d/99-allowed-users.conf"
    mode: "0640"
    validate: "sshd -T -f %s"
    content: |
      AllowUsers {{ username }}
  notify:
    - "Restart ssh"
