---
- name: "Include OS-specific variables"
  ansible.builtin.include_vars: "{{ ansible_os_family | lower }}.yml"
  tags: [required_for_boot]

- name: "Install OS-specific packages"
  ansible.builtin.include_tasks: "install-{{ ansible_os_family | lower }}.yml"
  tags: [required_for_boot]

- name: "Configure ssh"
  ansible.builtin.include_tasks: "configure.yml"
  tags: [required_for_boot]
