---
- name: "Set partition_list"
  ansible.builtin.set_fact:
    partition_list: "{{ [partition_boot, partition_swap, partition_root] + partition_extras }}"

- name: "Erase device: {{ partition_disk }}"
  ansible.builtin.command:
    cmd: "wipefs -af {{ partition_disk }}"
  when: partition_wipe
  changed_when: true

- name: "Run swapoff {{ partition_swap.dev }}"
  # Ensure unmounting swap partition as it's mounted using swapon
  ansible.builtin.command:
    cmd: "swapoff {{ partition_swap.dev }}"
  changed_when: "'molecule-idempotence-notest' not in ansible_skip_tags"
  failed_when: false

- name: "Ensure partitions are not mounted"
  ansible.posix.mount:
    src: "{{ item.dev }}"
    path: "{{ item.mount_path }}"
    state: "unmounted"
  # Ensure the /mnt/path is unmounted before /mnt (respect mount tree)
  # This ensures not getting error device is busy when unmounting
  with_items: "{{ partition_list | sort(attribute='mount_path') | reverse }}"
  changed_when: "'molecule-idempotence-notest' not in ansible_skip_tags"

- name: "Partition device: {{ partition_disk }}"
  community.general.parted:
    device: "{{ partition_disk }}"
    number: "{{ item.num }}"
    name: "{{ item.name }}"
    label: "{{ item.label | default('gpt') }}"
    flags: "{{ item.flags | default([]) }}"
    part_start: "{{ item.part_start }}"
    part_end: "{{ item.part_end }}"
    state: "present"
  with_items: "{{ partition_list }}"

- name: "Create filesystem on device: {{ partition_disk }}"
  community.general.filesystem:
    dev: "{{ item.dev }}"
    fstype: "{{ item.fstype }}"
    opts: "{{ item.fstype_opts | default(omit) }}"
    force: "{{ (item.name == partition_swap.name) | ternary(true, partition_wipe) }}"
  with_items: "{{ partition_list }}"
  changed_when: "'molecule-idempotence-notest' not in ansible_skip_tags"

- name: "Run mkswap"
  ansible.builtin.command:
    cmd: "mkswap {{ partition_swap.dev }}"
  changed_when: "'molecule-idempotence-notest' not in ansible_skip_tags"

- name: "Run swapon {{ partition_swap.dev }}"
  ansible.builtin.command:
    cmd: "swapon {{ partition_swap.dev }}"
  changed_when: "'molecule-idempotence-notest' not in ansible_skip_tags"

- name: "Mount partitions"
  ansible.posix.mount:
    src: "{{ item.dev }}"
    path: "{{ item.mount_path }}"
    fstype: "{{ item.fstype }}"
    opts: "{{ item.fstab_opts | default('defaults') }}"
    state: "mounted"
  # Ignore mounting swap partition as it's mounted using swapon
  when: item.name != partition_swap.name
  # Ensure the /mnt is mounted before /mnt/path (respect mount tree)
  with_items: "{{ partition_list | sort(attribute='mount_path') }}"
  changed_when: "'molecule-idempotence-notest' not in ansible_skip_tags"
