---
- name: "Reload systemd"
  become: true
  ansible.builtin.systemd_service:
    daemon_reload: true
  when: not ansible_is_chroot


- name: "Validate ssh"
  become: true
  ansible.builtin.command:
    cmd: "sshd -T -f /etc/ssh/sshd_config"
  changed_when: false
  when: not ansible_is_chroot

- name: "Restart ssh"
  become: true
  ansible.builtin.service:
    name: "{{ ssh_service_name }}"
    state: "restarted"
  when: not ansible_is_chroot
