---
- name: "Show hostname"
  ansible.builtin.debug:
    msg: "Run hostname: {{ hostname }}"
  tags: [required_for_boot]

- name: "Include roles for {{ hostname }}"
  ansible.builtin.include_role:
    name: "{{ item }}"
  with_items: "{{ (group_roles + host_roles) | unique }}"
  tags: [required_for_boot]
