---
role_name_check: 1
dependency:
  name: galaxy
  options:
    ignore-errors: true
    requirements-file: "requirements.yml"
driver:
  name: podman
platforms:
  - name: instance
    image: ${MOLECULE_DISTRO:-archlinux}
    dockerfile: Dockerfile.${MOLECULE_DISTRO:-archlinux}.j2
    pre_build_image: false
    privileged: true
    command: ${MOLECULE_COMMAND:-""}
    tmpfs:
      "/tmp": "rw"
      "/run": "rw,exec"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    cgroupns_mode: host
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "../../roles"
  playbooks:
    converge: converge.yml
verifier:
  name: ansible
