---
role_name_check: 1
dependency:
  name: galaxy
  options:
    ignore-errors: true
driver:
  name: podman
platforms:
  - name: instance
    image: ${MOLECULE_DISTRO:-archlinux}
    dockerfile: Dockerfile.${MOLECULE_DISTRO:-archlinux}.j2
    pre_build_image: false
    privileged: true
    command: ${MOLECULE_COMMAND:-""}
    tmpfs:
      "/tmp": "rw"
      "/run": "rw,exec"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    cgroupns_mode: host
provisioner:
  name: ansible
  inventory:
    links:
      host_vars: "../../host_vars/"
      group_vars: "../../group_vars/"
  env:
    MOLECULE_DISTRO: "${MOLECULE_DISTRO:-archlinux}"
    ANSIBLE_ROLES_PATH: "../../roles"
  config_options:
    defaults:
      callback_result_format: yaml
    ssh_connection:
      pipelining: true
  playbooks:
    converge: converge.yml
verifier:
  name: ansible
