---
argument_specs:
  main:
    options:
      hostname:
        type: "str"
        required: true
        description: "The distro linux hostname to be configured (will configure if availabe in inventory)"
      rc_playbooks_dir:
        type: "str"
        required: false
        default: "{{ playbook_dir }}"
        description: "The rc playbooks directory, defaults to ansible.playbook_dir variable"
      partition_boot:
        type: "dict"
        required: true
        description: "Check partition_boot argument in role: partition"
      partition_root:
        type: "dict"
        required: true
        description: "Check partition_root argument in role: partition"
