---
# Locales
settings_locales:
  - "en_US.UTF-8 UTF-8"
settings_locales_lang: "en_US.UTF-8"
settings_locales_language: "en_US:en:C"
settings_locales_lc_type: "en_US.UTF-8"
settings_locales_lc_numeric: "en_US.UTF-8"
settings_locales_lc_time: "C.UTF-8"
settings_locales_lc_collate: "C.UTF-8"
settings_locales_lc_monetary: "C.UTF-8"
settings_locales_lc_messages: "en_US.UTF-8"
settings_locales_lc_paper: "en_US.UTF-8"
settings_locales_lc_name: "en_US.UTF-8"
settings_locales_lc_address: "en_US.UTF-8"
settings_locales_lc_telephone: "en_US.UTF-8"
settings_locales_lc_measurement: "C.UTF-8"
settings_locales_lc_identification: "en_US.UTF-8"

# Timezone
settings_timezone: "UTC"

# Password policy
# https://linux.die.net/man/8/pam_pwquality
settings_pw_policy_enabled: true
settings_pw_policy_difok: 0
settings_pw_policy_minlen: 8
settings_pw_policy_dcredit: 0
settings_pw_policy_ucredit: 0
settings_pw_policy_ocredit: 0
settings_pw_policy_lcredit: 0
settings_pw_policy_minclass: 0
settings_pw_policy_maxrepeat: 0
settings_pw_policy_maxclassrepeat: 0
settings_pw_policy_gecoscheck: 0
