---
- name: "Update localtime"
  become: true
  ansible.builtin.file:
    src: "/usr/share/zoneinfo/{{ settings_timezone }}"
    dest: "/etc/localtime"
    state: link

- name: "Update locale.gen"
  become: true
  ansible.builtin.lineinfile:
    dest: "/etc/locale.gen"
    mode: "0644"
    regexp: "^#{{ item }}"
    line: "{{ item }}"
  with_items: "{{ settings_locales }}"
  notify: "Run locale-gen"

- name: "Update locale.conf"
  become: true
  ansible.builtin.copy:
    dest: "/etc/locale.conf"
    mode: "0644"
    content: |
      LANG={{ settings_locales_lang }}
      LANGUAGE={{ settings_locales_language }}
      LC_CTYPE="{{ settings_locales_lc_type }}"
      LC_NUMERIC={{ settings_locales_lc_numeric }}
      LC_TIME={{ settings_locales_lc_time }}
      LC_COLLATE="{{ settings_locales_lc_collate }}"
      LC_MONETARY={{ settings_locales_lc_monetary }}
      LC_MESSAGES="{{ settings_locales_lc_messages }}"
      LC_PAPER={{ settings_locales_lc_paper }}
      LC_NAME={{ settings_locales_lc_name }}
      LC_ADDRESS={{ settings_locales_lc_address }}
      LC_TELEPHONE={{ settings_locales_lc_telephone }}
      LC_MEASUREMENT={{ settings_locales_lc_measurement }}
      LC_IDENTIFICATION={{ settings_locales_lc_identification }}
