---
- name: "Configure archlinux password policy"
  become: true
  ansible.builtin.template:
    src: "archlinux-pam-pw.j2"
    dest: "/etc/pam.d/system-auth"
    mode: "0644"
  when: ansible_os_family == "Archlinux"

- name: "Configure debian password policy"
  become: true
  ansible.builtin.template:
    src: "debian-pam-pw.j2"
    dest: "/etc/pam.d/common-password"
    mode: "0644"
  when: ansible_os_family == "Debian"
