---
- name: "Set root,boot partition paths"
  ansible.builtin.set_fact:
    install_boot_path: "{{ partition_boot.mount_path }}"
    install_root_path: "{{ partition_root.mount_path }}"

- name: "Install archlinux tasks"
  ansible.builtin.include_tasks: "install-archlinux.yml"
  when: ansible_os_family == "Archlinux"

- name: "Install debian tasks"
  ansible.builtin.include_tasks: "install-debian.yml"
  when: ansible_os_family == "Debian"

- name: "Install ansible-core on live environment"
  # Can't install ansible-core using package manager
  # This resolve the "ERROR! ansible-galaxy requires resolvelib<1.1.1,>=0.5.3"
  # where the python-resolvelib was updated but ansible package wasn't in the package managers
  ansible.builtin.pip:
    name: "ansible-core>=2.18"
    state: "present"
    break_system_packages: true

- name: "Run distro-configure"
  ansible.builtin.include_tasks: "run-distro-configure.yml"
